version: "3.8"
volumes: 
  mosquitto_data: {}
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883" 
      - "9001:9001"
    volumes: 
      - mosquitto_data:/mosquitto/
      - ./mosquitto/config/:/mosquitto/config:ro