global:
  scrape_interval: 5s
  external_labels:
    monitor: 'myprom'
rule_files:
  - 'alert.rules/*.yml'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: [prometheus:9090] 
  - job_name: 'mqttgateway'
    static_configs:
      - targets: [mqttgateway:9337]