{
 "title": "DHT22",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Pump", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pumpe",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Angle" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Pump" }
   ]
  },
  {
   "title": "Pumpenzeit seit letztem Auffüllen",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum_over_time(Pump[1y]) / 12", "legendFormat": "Minuten" }
   ]
  },
  {
   "title": "Pumpenzeit letzte Stunde",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum_over_time(Pump[60m]) / 12", "legendFormat": "Minuten" }
   ]
  },
  { "title": "Soil", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Raw Soil Moisture",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "soil_moisture_value", "legendFormat": "raw" }
   ]
  },
  {
   "title": "Soil Moisture %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "soil_moisture_percent", "legendFormat": "%" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "humidity", "legendFormat": "%" }
   ]
  },
  {
   "title": "Average Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg_over_time(humidity[60m])" }
   ]
  },
  { "title": "Heat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Ambient Temperature Celsius",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "temperature_celsius", "legendFormat": "°C" }
   ]
  },
  {
   "title": "Gefühlte Temperatur",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "heat_index" }
   ]
  },
  {
   "title": "Average Temp Last Hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(temperature_celsius[60m])"
    }
   ]
  },
  { "title": "Humid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } }
 ]
}